=== HelloYing/5234/XMLfile/profile.dtd
<!ELEMENT profile (name, birthday, phone, address, balance,eventId, point)>
        <!ATTLIST profile id ID #REQUIRED>
   <!ELEMENT name (username,firstname,lastname)>
   		<!ELEMENT username (#PCDATA)>
   		<!ELEMENT firstname (#PCDATA)>
   		<!ELEMENT lastname (#PCDATA)>
    <!ELEMENT birthday (month, day, year)>
        <!ELEMENT month (#PCDATA)>
        <!ELEMENT day (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT address (No, street, city, state, room)>
        <!ELEMENT No (#PCDATA)>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT state (#PCDATA)>
        <!ELEMENT room (#PCDATA)>
    <!ELEMENT balance (#PCDATA)>
    <!ELEMENT point (#PCDATA)>
    <!ELEMENT eventId ANY>

=== HelloYing/5234/XMLfile/profile.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="U3" >
    <name>
           <username>ABC</username>
           <firstname>Adom</firstname>
           <lastname>King</lastname>
    </name>    
    <birthday>
           <month>--10</month>
           <day>---25</day>
           <year>2014</year>
    </birthday>
    <phone>ABC</phone>
    <address>
        <No>1</No>
        <street>neil</street>
        <city>columbus</city>
        <state>ohio</state>
        <room>35</room>
    </address>
    <balance>0.00</balance>
    <eventId>12</eventId>
    <point>10</point>
</profile>
